INSERT INTO entities VALUES (0, 'someEntity');
INSERT INTO components (name) VALUES ('someComponent');
INSERT INTO records (name) VALUES ('record1');
/* double */
INSERT INTO valuemapping (entity_id, component_id, value_timestamp) VALUES (0,1,now());
INSERT INTO recordmapping VALUES (1, 1);
INSERT INTO values_double VALUES (1, 2.3536);
/* string */
INSERT INTO valuemapping (entity_id, component_id, value_timestamp) VALUES (0,1,now());
INSERT INTO recordmapping VALUES (1, 2);
INSERT INTO values_string VALUES (2, 'some string');
/* double array */
INSERT INTO valuemapping (entity_id, component_id, value_timestamp) VALUES (0,1,now());
INSERT INTO recordmapping VALUES (1, 3);
INSERT INTO values_double_array VALUES (3, '{9.2453, 36.436347}');
